version: '3'

services:

  redis:
    image: redis
    ports:
        - "6379:6379"

  dbpostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: myTopic
    links:
      - zookeeper
      
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  